#ifndef _GEN_PRECOM_H
#define _GEN_PRECOM_H

#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/event.h>
#include <sys/queue.h>
#include <sys/tree.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <sys/utsname.h>
#include <sys/param.h>
#include <sys/time.h>
#include <sys/sysctl.h>
#include <sys/uio.h>
#include <sys/wait.h>
#include <sys/mount.h>
#include <sys/limits.h>
#include <sys/statvfs.h>
#include <sys/resource.h>
#include <sys/module.h>
#include <sys/linker.h>
#include <sys/times.h>
#include <sys/param.h>
#include <sys/user.h>
#include <sys/sysctl.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <sys/sem.h>
#include <sys/msg.h>

#include <net/if.h>
#include <net/route.h>
#include <net/if_dl.h>
#include <net/bpf.h>
#include <net/if_var.h>
#include <net/if_types.h>
#include <net/ethernet.h>
#include <net/if_lagg.h>
#include <net/if_arp.h>
#include <net/if_bridgevar.h>
#include <net/if.h>
#include <net/if_var.h>
#include <net/if_vlan_var.h>
#include <net/ieee8023ad_lacp.h>
#include <net/if_media.h>

#include <netinet/tcp_fsm.h>
#include <netinet/in.h>
#include <netinet6/in6_var.h>
#include <netinet6/nd6.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <netinet/if_ether.h>
#include <netinet/ip_carp.h>

#include <arpa/inet.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <err.h>
#include <fcntl.h>
#include <time.h>
#include <unistd.h>
#include <stdarg.h>
#include <syslog.h>
#include <signal.h>
#include <pthread.h>
#include <pthread_np.h>
#include <ifaddrs.h>
#include <netdb.h>
#include <dirent.h>
#include <assert.h>
#include <stdint.h>
#include <nlist.h>
#include <dlfcn.h>
#include <inttypes.h>
#include <math.h>
#include <poll.h>

#endif
